### ISSUE TITLE
Reset Password Flow Using GeneratePasswordResetTokenAsync

### ISSUE THREAD

**Issue by joseph-adam** [aws/aws-aspnet-cognito-identity-provider#109]
It seems if you use GeneratePasswordResetTokenAsync to generate your own reset token it will not work in conjunction with ResetPasswordAsync.  It may be that the only way to initiate a password reset flow is to have Cognito generate the password reset email directly.

**Comment by assyadh** [comment]
Hi,

You can have a look at this doc explaining which api to call for the reset workflow:

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/docs/5-User%20Management%20-%20Change%20and%20reset%20passwords.md

The apis are slightly different due to the nature of the workflow difference between Identity and Cognito.

As you mentioned, Cognito can not 'generate' a token, it only 'sends' a token to email, Hence the apis mentioned in the docs!

**Comment by klaytaybai** [comment]
> A doubt.
> Is there a way for admin to create a new password without being interacted by email?
@fnalin, https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminSetUserPassword.html

**Comment by fnalin** [comment]
@klaytaybai tks
worked perfectly
