### ISSUE TITLE
stay logged in

### ISSUE THREAD

**Issue by ghendo** [aws/aws-aspnet-cognito-identity-provider#122]
I find that no matter what settings I use in the startup I can never have users logged in for more than around 30 min.  I am beginning to suspect cognito is causing this?  Is this possible?

**Comment by avaleri** [comment]
I have the same problem with my project. 

It seems to be related to this issue:

https://github.com/aspnet/Identity/pull/1941

I was able to increase the session timeout by adding this code, and the Validation Interval specified in this new code block controls how long the session is valid for.

            services.Configure<SecurityStampValidatorOptions>(options =>
            {
                options.ValidationInterval = TimeSpan.FromHours(1);
            });

**Comment by kwood0912** [comment]
I also have been dealing with the same problem.  It seems that no matter what settings I used when configuring the application cookie in Startup.cs the application identity cookie generated by the Cognito identity provider was set to expire in one hour.  I was able to find a solution that resolves this for standard password sign in.

In Startup.cs:
```           
services.AddCognitoIdentity(options =>
{
	options.SignIn.RequireConfirmedEmail = true;
	options.User.RequireUniqueEmail = true;
});

services.ConfigureApplicationCookie(options =>
{
	options.Cookie.HttpOnly = true;
	options.AccessDeniedPath = new PathString("/access-denied");
	options.LogoutPath = new PathString("/logout");
	options.LoginPath = new PathString("/login");
	options.SlidingExpiration = true;
});
```

In Sign In action:
```
var cognitoUser = await _userManager.FindByEmailAsync(model.Email);
if (cognitoUser != null)
{
    var signInResult = await _signInManager.CheckPasswordSignInAsync(cognitoUser, model.Password, lockoutOnFailure: false);
    if (signInResult.Succeeded)
    {
	await _signInManager.SignInAsync(cognitoUser, 
	    new AuthenticationProperties()
	    {
	        AllowRefresh = true,
		IssuedUtc = DateTime.UtcNow,
		ExpiresUtc = DateTime.UtcNow.AddDays(15),
		IsPersistent = model.RememberMe
	    });
    }
}
```
When signing the user in via the method above, the application identity cookie was generated with an expiration date 15 days in the future instead of just one hour into the future.  I hope this helps.

**Comment by MarneeDear** [comment]
@kwood0912 I tried your approach with the sign in, but it seems if you don't use PasswordSignInAsync, the user isn't really signed in and doing things like changing the email address and trying to send a confirmation code don't work. You get an error message about the member being null. Have you seen this problem?

**Comment by ashishdhingra** [comment]
Hi @ghendo,

Please confirm if solution provided by @kwood0912 worked for you and if this issue could be closed.

Thanks,
Ashish

**Comment by ghendo** [comment]
No this problem is not solved

**Comment by duaneking** [comment]
What is the status of this active issue?

**Comment by ashishdhingra** [comment]
Hi @ghendo / @kwood0912,

Good afternoon.

Based on debugging, following is the code flow of the application: `[CognitoSignInManager]`::`.PasswordSignInAsync(string,string,bool,bool)` **->** `PasswordSignInAsync(TUser,string,bool,bool)` **->** `CheckPasswordSignInAsync(TUser,string,bool)` **->** `SignInAsync(TUser,bool,string)`.

The SignInAsync() populates the `AuthenticationProperties`:
```
var authenticationProperties = new AuthenticationProperties
{
    IsPersistent = isPersistent,
    AllowRefresh = true,
    ExpiresUtc = user.SessionTokens?.ExpirationTime,
    IssuedUtc = user.SessionTokens?.IssuedTime
};
```
It sets the `ExpiresUtc` as the value from the SessionToken's ExpirationTime, whose value is determined by App Client's `Access token expiration` setting (default is 60 minutes) for a user pool. As noted by AWS Cognito Console, this setting `Must be between 5 minutes and 1 day. Cannot be greater than refresh token expiration`. Since the Access Token would expire after this interval, the current implementation for expiring the application cookie appears to be correct. Using Refresh Token to get the new Access Token resets the expiration time of the application cookie by using the same logic mentioned above.

You may check your `Access token expiration` setting for app client and if necessary, try increasing the value within the limited range as specified in the AWS console.

Hope this helps. Kindly let me know if anything else is required.

Thanks,
Ashish
