### ISSUE TITLE
Can I use this with the .NET Core 3.0 SPA project structure?

### ISSUE THREAD

**Issue by andyfurniss4** [aws/aws-aspnet-cognito-identity-provider#137]
I've been looking at the SPA project templates that were introduced with .NET Core 3.0 and trying to figure out if there's a way to switch out the default user store (Entity Framework) for Cognito but so far I haven't found a way.

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0

Have you experimented with this at all? Is there a way to use Cognito with this new project structure?

**Comment by Fydar** [comment]
I have been using this with ASP.NET Core 3.0 since the preview releases of it and it works fine for me. I am using a SPA Blazor application with a separate, restful login page.

When you inject the Cognito Identify Provider using `services.AddCognitoIdentity ();` (as documented on the README.md) you are replacing the default user store.

Not much has changed with the advent of .NET Core 3.0 SPA project templates.

**Comment by horizondave** [comment]
@Fydar Would love to see a sample ASP.NET Core 3.0/3.1 app using Cognito Identity.  I am lurching from one crash to another as I discover all the undocumented requirements (The latest being that ConfirmAccount doesn't work for me as my user has no claims....Probably due to the [AllowAnonymous] attribute on the RazorPages code?!)

**Comment by ashishdhingra** [comment]
Hi @andyfurniss4,

Good morning.

I came across this backlog issue and notice that @Fydar had already provided the input. Please confirm if this issue could be closed.

Thanks,
Ashish

**Comment by andyfurniss4** [comment]
@ashishdhingra Yes, feel free to close. Thanks.
