### ISSUE TITLE
NotSupportedException: Store does not implement IUserAuthenticatorKeyStore<User>.

### ISSUE THREAD

**Issue by jandvs** [aws/aws-aspnet-cognito-identity-provider#156]
I'm trying to setup 2FA using an authenticator app.. I don't see a lot of examples of doing this, but I think it starts with a call to `userManager.GetAuthenticatorKeyAsync(user)` where user is of type `CognitoUser`.  But this call throws the exception below.

Also the call to `userManager.GetValidTwoFactorProvidersAsync(user)` throws the same exception.

```
NotSupportedException: Store does not implement IUserAuthenticatorKeyStore<User>.
Microsoft.AspNetCore.Identity.UserManager<TUser>.GetAuthenticatorKeyStore()
```

Stack Query Cookies Headers
```
NotSupportedException: Store does not implement IUserAuthenticatorKeyStore<User>.
Microsoft.AspNetCore.Identity.UserManager<TUser>.GetAuthenticatorKeyStore()
Microsoft.AspNetCore.Identity.UserManager<TUser>.GetAuthenticatorKeyAsync(TUser user)
LoginAppCognito.Areas.Identity.Pages.Account.LoginModel.OnGetAsync(string returnUrl) in Login.cshtml.cs
+
                var AuthenticatorKey = await _userManager.GetAuthenticatorKeyAsync(user);
```

**Comment by ashishdhingra** [comment]
Hi @jandvs, 

Please confirm if this is still an issue. Also request you to provide more details in the following format along with the use case and sample code:



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 


Thanks,
Ashish
