### ISSUE TITLE
The Areas/Identity/Services folder includes in Samples.csproj does not exist

### ISSUE THREAD

**Issue by alexisatkinson** [aws/aws-aspnet-cognito-identity-provider#172]
https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/e54f03d7854e17b05434ed34a3c67fa992ffe45c/samples/Samples/Samples.csproj#L16

It looks like this just needs to be removed from the project file.

**Comment by ashishdhingra** [comment]
Hi @alexisatkinson,

Good afternoon.

Thanks for reporting the issue. I'm not sure on how this impacts the sample solution, but since this is not a bug in SDK, I'm not sure on the timeline when this could be fixed. However, I can definitely have developer look at it and implement this simple change.

Thanks,
Ashish

**Comment by genifycom** [comment]
Further, the Samples use DotNet 2.1 which is outdated.

**Comment by ashishdhingra** [comment]
PR https://github.com/aws/aws-aspnet-cognito-identity-provider/pull/174 merged.
