### ISSUE TITLE
ChangePasswordAsync fails for certain User Pools

### ISSUE THREAD

**Issue by genifycom** [aws/aws-aspnet-cognito-identity-provider#182]
I have been testing with Amazon.AspNetCore.Identity.Cognito and Amazon.Extensions.CognitoAuthentication in a DotNet Core 3.1 Lambda Web Application.

If I create a Cognito User Pool using "Username - Users can use a username and optionally multiple alternatives to sign up and sign in." then the ChangePasswordAsync succeeds in changing the password.

However, if I choose "Email address or phone number - Users can use an email address or phone number as their "username" to sign up and sign in.", and "Allow email addresses" then: 

`var user = await _userManager.FindByEmailAsync(Input.Email);`

succeeds and find the correct user, but the:

`var result = await _userManager.ChangePasswordAsync(user, Input.CurrentPassword, Input.NewPassword);`

always fails with PasswordMismatch

The current password is correct and the new password conforms to the rules.

I would like to use email as the username.

In addition, it I set the password manually using **aws cognito-idp admin-set-user-password** then the 

`var result = await _signInManager.PasswordSignInAsync(Input.UserName, Input.Password, Input.RememberMe, lockoutOnFailure: false);`

fails with invalid login attempt. I have tried with both the email and the sub for the user but no go.

Has anyone else seen this issue?

**Comment by ashishdhingra** [comment]
Hi @genifycom,

Good morning.

Thanks for reporting the issue.

In order to effectively reproduce this issue, please share the following:
- Cognito User Pool settings in AWS Console.
- Sample code solution, if possible.
- Does this work if you execute the flow within Console application or is it the issue from within Lambda only?
- Lambda web application settings.

In the meanwhile, I will try to do some analysis at my end.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
Hi @genifycom,

Good morning.

I have tried to reproduce the issue reported by you using the sample solution provided in the repository https://github.com/aws/aws-aspnet-cognito-identity-provider/tree/master/samples. Using (upgrading) the mentioned NuGet package versions, the ChangePassword scenario works fine. The user pool has been configured with:
- **Email address or phone number** to sign in
- AppClient has all the Auth Flow(s) enabled.

I'm not sure what to suggest since the issue is not reproducible. Is it possible to share the sample code solution, and all of you user pool and app client settings in AWS Cognito console?

Thanks,
Ashish

**Comment by genifycom** [comment]
Hi Ashish,

I have the sample project created and tested and it continues to get a password mismatch.

How can I dump the Cognito User Pool settings? Screen shots of each of the pages?

Also the project obviously contains my keys so how do I get this to you in a testable state, just xxx out the private information?

Please advise.

Thanks<
Dave

**Comment by ashishdhingra** [comment]
Hi @genifycom,

You may want to exclude the sensitive information from your code, including keys, and share the minimal code to reproduce the issue. For Cognito user pool settings, you may list down the high level information (screenshots are preferable though).

Thanks,
Ashish

**Comment by genifycom** [comment]
Sure. Starting with the User Pool. I tried to pick the minimal requirements just using email.

<img width="919" alt="Cognito0" src="https://user-images.githubusercontent.com/24735929/99702787-7c3da900-2a53-11eb-93de-8641274a49af.PNG">
<img width="799" alt="Cognito1" src="https://user-images.githubusercontent.com/24735929/99702796-7ea00300-2a53-11eb-97f3-45ef23a401b4.PNG">
<img width="863" alt="Cognito2" src="https://user-images.githubusercontent.com/24735929/99702799-8069c680-2a53-11eb-9ade-9c9b30820dbe.PNG">
<img width="926" alt="Cognito3" src="https://user-images.githubusercontent.com/24735929/99702806-82338a00-2a53-11eb-9c77-70221db806bc.PNG">
<img width="922" alt="Cognito4" src="https://user-images.githubusercontent.com/24735929/99702811-83fd4d80-2a53-11eb-8c3b-c94280c9b91e.PNG">

**Comment by genifycom** [comment]
Then I create a user with:

aws cognito-idp admin-create-user --user-pool-id <poolid> --username <myemail> --user-attributes Name=given_name,Value=XXX Name=family_name,Value=YYY Name=email,Value=<myemail> --temporary-password Test1_Test2

Running the app, the initial Login using email and the temporary password works fine and I see

<img width="695" alt="Initial Login" src="https://user-images.githubusercontent.com/24735929/99703811-cd9a6800-2a54-11eb-947b-cce3fe2ffc4e.PNG">

This then flips me over to the ChangePassword screen. I use the email, Test1_Test2 as the current password (the temporary one) and the new password AltTest_1199

Here, the: `var user = await _userManager.FindByEmailAsync(Input.Email);` works and returns the user.
But the next part ` var result = await _userManager.ChangePasswordAsync(user, Input.CurrentPassword, Input.NewPassword);` fails like this
<img width="528" alt="Change Password" src="https://user-images.githubusercontent.com/24735929/99704206-4b5e7380-2a55-11eb-9bf8-519cfc69d8eb.PNG">

**Comment by genifycom** [comment]
This project uses the Identity Area from the Cognito samples project.
[AWSCognitoTest.zip](https://github.com/aws/aws-aspnet-cognito-identity-provider/files/5568775/AWSCognitoTest.zip)

**Comment by ashishdhingra** [comment]
Hi @genifycom,

Please confirm if you are using the same solution as in the `sample` folder in this repository. If not, it would be helpful to share the complete solution (you should be able to ZIP the solution with sensitive information removed and drag and drop to Comment are to upload) so that I can troubleshoot the issue. I will try to reproduce the issue with the user pool settings you provided, I guess these are similar to one I used earlier (and the change password flow worked fine for me), but would give it one more try.

Thanks,
Ashish

**Comment by genifycom** [comment]
Ok thank you. I have tried this multiple times as I really do not want to have to use username.

**Comment by ashishdhingra** [comment]
Hi @genifycom,

I tried using your sample code and the change password flow works fine for me (please refer screenshot below):
<img width="1609" alt="Screen Shot 2020-11-19 at 12 38 48 PM" src="https://user-images.githubusercontent.com/67916761/99721591-5076ef00-2a64-11eb-8fd5-65ae39835ab1.png">

NOTE: I used the `appsettings.Development.json` as shown below, instead of hardcoding the Cognito IDP values in code:
```JSON
{
  "AWS": {
    "Region": "<region>",
    "UserPoolClientId": "<userpool_clientid>",
    "UserPoolClientSecret": "<userpool_clientsecret>",
    "UserPoolId": "<userpool_id>"
  }
}
``` 
Hence, I commented the below code (except `services.AddCognitoIdentity()` call):
```C#
//#region Cognito
//var cognitoIdentityProvider = new AmazonCognitoIdentityProviderClient(aws_access_key, aws_secret_key, USWest2);
//var cognitoUserPool = new CognitoUserPool(PFAdminUsersPoolId, PFAdminUsersClientId, cognitoIdentityProvider);

////https://github.com/aws/aws-aspnet-cognito-identity-provider
//// Adds your own instance of Amazon Cognito clients cognitoIdentityProvider and cognitoUserPool are variables you would have instantiated yourself
//services.AddSingleton<IAmazonCognitoIdentityProvider>(cognitoIdentityProvider);
//services.AddSingleton<CognitoUserPool>(cognitoUserPool);

// Adds Amazon Cognito as Identity Provider
//https://aws.amazon.com/blogs/developer/now-generally-available-the-asp-net-core-identity-provider-for-amazon-cognito/
services.AddCognitoIdentity();
//#endregion Cognito
```

I do notice that you are not using client secret for you user pool app client.

Here are my app client settings (you may compare the settings at your end):
<img width="1076" alt="Screen Shot 2020-11-19 at 12 46 01 PM" src="https://user-images.githubusercontent.com/67916761/99722308-56210480-2a65-11eb-98b6-e7997c285eff.png">

The error in your screenshot indicates the incorrect password. I'm not sure if you are typing the correct password in the change password flow. Everything works fine at my end. I'm not sure what further guidance could be provided here.

Thanks,
Ashish

**Comment by genifycom** [comment]
Ok, I will try two things. 1. a region other then us-west-2 (just in case) and 2. using the appsettings approach. I had read this https://www.gitmemory.com/issue/aws/aws-aspnet-cognito-identity-provider/124/530445186 on the UserPoolClientSecret so I assumed it was optional and I was not using it.

On copying the password, I have been very careful to ensure that the password was copied directly and in addition I tried this same test with different users and on different client accounts, all with the same result.

I will try your appClient settings and let you know the result.

Thank you for your feedback.

**Comment by genifycom** [comment]
Thanks Ashish,

I found that client secret is absolutely required (it is not optional) and ChangePassword now succeeds.

Apologies for using your time.

Thank you so much for looking at this.

Regards,
Dave
