### ISSUE TITLE
Populate session tokens

### ISSUE THREAD

**Issue by aussiearef** [aws/aws-aspnet-cognito-identity-provider#34]
Is there any attributes which would return an access token or Id Token for client-side authentication?

**Comment by assyadh** [comment]
Hi @aussiearef,

Can you explain your use case?

H.

**Comment by gopinathrimc** [comment]
In my i have both API and Razor page.  I have secured the API with Bearer tokens authentication. 
On the Razor page am able to use the SignInManager.IsSignedIn(User) to check if the user is signed in, and for the API i want to pass in bearer token. 
So login to the app i want to access the session token and cache the id token on the client so that on api request i can send in the id token.

So how do i go about accessing the idtoken once i have signed in using PasswordSignInAsync?

**Comment by jobairkhan** [comment]
If the user has permission to access another secured API. I believe the following code should return me the access_token, that I should be able to use to retrieve data from another API

```CSharp
var token = await HttpContext.GetTokenAsync("access_token").ConfigureAwait(false);
```
at the moment the value of the variable `token` is null even though the user is authenticated

**Comment by assyadh** [comment]
Once you Sign in, the CognitoUser instance has the AccessToken object populated. I am looking into incorporating Identity apis with this.

**Comment by assyadh** [comment]
See https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs#L40

**Comment by assyadh** [comment]
I have a PR in to expose tokens through HttpContext.GetTokenAsync(). I will let you know when this is released

**Comment by assyadh** [comment]
Hi, [0.9.0.7](https://www.nuget.org/packages/Amazon.AspNetCore.Identity.Cognito/0.9.0.7) now exposes the token through HttpContext.GetTokenAsync(): 

See: https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/src/Amazon.AspNetCore.Identity.Cognito/CognitoSigninManager.cs#L141
