### ISSUE TITLE
Reset password flow

### ISSUE THREAD

**Issue by andyfurniss4** [aws/aws-aspnet-cognito-identity-provider#44]
What's the correct flow for when a password is reset in Cognito (AWS console or otherwise)? When I do this and sign in I get a `RequiresPasswordChange = true` response as expected but when I subsequently call `userManager.ChangePasswordAsync()` with the user, old password and new password I then get the following error: 

> Failed to change the Cognito User password : Password reset required for the user

I thought that maybe I should be using `ResetPasswordAsync` instead but there doesn't seem to be a way of discerning between when a ChangePassword is required and when a ResetPassword is required based on the log in result. Both the result for an admin-created user's first login and a when a user's password has been reset by an admin is `RequiresPasswordChange = true`.

Thanks

**Comment by jlwhitfill** [comment]
It seems there are some quirks in this as the ForgotPassword should require some sort of email or sms code to change it since the user is not logged in, while the ChangePassword is done when the user is logged in and requires no code.  Im working with the forgot password portion and have scaffolded in the ForgotPassword item for the .Net Identity, but I cant seem to find how to generate that email to get the code....there has already been a request to add some examples but they are not up there yet.  I would love to see how the flow is supposed to be in BOTH cases where the password is changed

**Comment by assyadh** [comment]
Hi @andyfurniss4 

Thanks for the feedback, I will add a different SigninResult to discern between a change password and a hard reset required.

@jlwhitfill Calling UserManager.ResetPasswordAsync(TUser user) will send the token to the user via email or sms depending on the User Pool policy.
You then have to call UserManager.ResetPasswordAsync(TUser user, string token, string newPassword)  with the new password and token. This will change the user password.

**Comment by jlwhitfill** [comment]
The ForgotPassword piece works for me now, thank you!

**Comment by assyadh** [comment]
Hi @andyfurniss4 , the following PR should solve the issue. Will let you know when it's available on NuGet:

https://github.com/aws/aws-aspnet-cognito-identity-provider/pull/45
